---
- hosts: 172.31.31.154
  become: yes
  tasks:

  - name: i want to install web server on ansbile node
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"

  - name: i want to start my webserver 
    service:
      name: apache2
      state: started
    when: ansible_os_family =="Debian"